# Generated by Django 2.2.12 on 2020-11-30 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldType', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('deviceName', models.CharField(max_length=64)),
                ('fieldNameOne', models.CharField(max_length=64)),
                ('fieldNameTwo', models.CharField(max_length=64)),
                ('fieldNameThree', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=64)),
                ('enable', models.CharField(max_length=64)),
                ('response', models.CharField(max_length=64)),
                ('fieldTypeOne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fieldOne', to='iotDash.Fields')),
                ('fieldTypeThree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fieldThree', to='iotDash.Fields')),
                ('fieldTypeTwo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fieldTwo', to='iotDash.Fields')),
            ],
        ),
    ]
