# Generated by Django 2.2.12 on 2020-12-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotDash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='enable',
            field=models.BooleanField(max_length=64),
        ),
        migrations.AlterField(
            model_name='devices',
            name='response',
            field=models.BooleanField(max_length=64),
        ),
    ]
