# Generated by Django 2.2.12 on 2020-12-06 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iotDash', '0002_auto_20201203_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('fieldDataOne', models.CharField(max_length=64)),
                ('fieldDataTwo', models.CharField(max_length=64)),
                ('fieldDataThree', models.CharField(max_length=64)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('remoteIP', models.FloatField()),
                ('deviceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Device', to='iotDash.Devices')),
            ],
        ),
    ]
