# Generated by Django 2.2.12 on 2020-12-06 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iotDash', '0003_devicedata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicedata',
            old_name='user',
            new_name='username',
        ),
    ]
