# Generated by Django 2.2.12 on 2020-12-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotDash', '0004_auto_20201206_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedata',
            name='remoteIP',
            field=models.CharField(max_length=64),
        ),
    ]
